import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/homepage/navbar/Navbar";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased md:px-[15vw] sm:px-0 bg-background text-foreground`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
